# Generated by Django 4.0.6 on 2022-10-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrante',
            name='edad',
            field=models.CharField(default='12', max_length=3),
        ),
    ]
